var arr = ["a", 1, true, { b: 6 }];
var arr2 = [123456];
var resulttoString = arr.toString();
var resultJoin = arr.join(" ");
var resultPop = arr.pop();
var resultPush = arr.push(5, 6);
var resultShift = arr.shift();
var resultUnshift = arr.unshift("a");
var resultSplicing = arr.splice("1", 1);
var resultConcat = arr.concat(arr2);
var resultSlice = arr.slice(1, 2);
console.log(resulttoString);
console.log(resultJoin);
console.log(resultPop.resultPop);
console.log(resultPush, arr);
console.log(resultShift);
console.log(resultUnshift);
console.log(resultSplicing);
console.log(resultConcat);
console.log(resultSlice)
